name = "cloud-mail2"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail-db"
database_id = "1e36d93e-d28d-4dd6-9c1e-06e78dba6c66"

[[kv_namespaces]]
binding = "kv"
id = "5dbfb562e7dc421d84db7c6ab68b3a35"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
orm_log = false
domain = ["dtsddh.dpdns.org"]
admin = "dtsfo@dtsddh.dpdns.org"
jwt_secret = "ae4f112080dd1bfc5296dcbb4e6af69891a8babe800c895554a742b09371b69a"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
